export enum ActionType {
  UPDATE_PERSONAL_DETAIL_DATA = 'update_personal_detail_data',
  UPDATE_PROFESSIONAL_SUMMARY_DATA = 'update_professional_summary_data',
  ADD_EMPLOYMENT_HISTORY_DATA = 'add_employment_history_data',
  UPDATE_EMPLOYMENT_HISTORY_DATA = 'update_employment_history_data',
  DELETE_EMPLOYMENT_HISTORY_DATA = 'delete_employment_history_data',
  MOVE_EMPLOYMENT_HISTORY_DATA = 'move_employment_history_data',
  ADD_EDUCATION_DATA = 'add_education_data',
  UPDATE_EDUCATION_DATA = 'update_education_data',
  DELETE_EDUCATION_DATA = 'delete_education_data',
  MOVE_EDUCATION_DATA = 'move_education_data',
  ADD_WEBSITES_SOCIAL_LINKS_DATA = 'add_websites_social_links',
  UPDATE_WEBSITES_SOCIAL_LINKS_DATA = 'update_websites_social_links_data',
  DELETE_WEBSITES_SOCIAL_LINKS_DATA = 'delete_websites_social_links_data',
  MOVE_WEBSITES_SOCIAL_LINKS_DATA = 'move_websites_social_links_data',
  ADD_LANGUAGES_DATA = 'add_languages_data',
  UPDATE_LANGUAGES_DATA = 'update_languages_data',
  DELETE_LANGUAGES_DATA = 'delete_languages_data',
  MOVE_LANGUAGES_DATA = 'move_languages_data',
  ADD_SKILLS_DATA = 'add_skills_data',
  UPDATE_SKILLS_DATA = 'update_skills_data',
  DELETE_SKILLS_DATA = 'delete_skills_data',
  MOVE_SKILLS_DATA = 'move_skills_data',
}
